name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release: 
    strategy:
      matrix:
        package:
          - opentelemetry-aws-xray
          - opentelemetry-broadway
          - opentelemetry-cowboy
          - opentelemetry-dataloader
          - opentelemetry-ecto
          - opentelemetry-elli
          - opentelemetry-finch
          - opentelemetry-grpcbox
          - opentelemetry-httpoison
          - opentelemetry-nebulex
          - opentelemetry-oban
          - opentelemetry-phoenix
          - opentelemetry-bandit
          - opentelemetry-process-propagator
          - opentelemetry-redix
          - opentelemetry-req
          - opentelemetry-telemetry
          - opentelemetry-tesla
          - opentelemetry-xandra
          - otel-http
    permissions:
      contents: write
      pull-requests: write      
    uses: ./.github/workflows/_release_drafter.yml
    with:
      package: ${{ matrix.package }}
  